SET DB_CLOSE_DELAY -1;         
;              
CREATE USER IF NOT EXISTS "SA" SALT '73e6f6ecdf7bf65d' HASH '692e3f39b6f3238fd3cf9b49573a9cfe5e928ecaa762bfd87e58fdc477517b61' ADMIN;          
CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 1;    
CREATE MEMORY TABLE "PUBLIC"."STATEMENT"(
    "ID" BIGINT NOT NULL,
    "CONTENT" CLOB,
    "CREATED" TIMESTAMP,
    "TITLE" VARCHAR(255),
    "USER_ID" BIGINT
);             
ALTER TABLE "PUBLIC"."STATEMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.STATEMENT;
CREATE MEMORY TABLE "PUBLIC"."USER"(
    "ID" BIGINT NOT NULL,
    "PASSWORD" VARCHAR(255),
    "USERNAME" VARCHAR(255)
);     
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_27" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER;     
ALTER TABLE "PUBLIC"."STATEMENT" ADD CONSTRAINT "PUBLIC"."FK8IM2JQSMYCG18VHUK7VUYOSHU" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;        
